vision:
    camera:
      show_image: false

    calibration: 
        calibrate_match_matrix: false
        calibrate_rectify_matrix: false
        calibrate_team_color: false

    object_list:
     # - "dummy_object" 
     - "ball"
     - "our_robots"
     - "opponent_robots"

    ball:
      segmentation_algorithm: "BallInRangeColorSegmentation"
      identification_algorithm: "BallIdentification"

    our_robots:
      segmentation_algorithm: "FindRobotsColor"
      segmentation_arguments: "Blue"
      identification_algorithm: "RobotIdentification"
      identification_arguments: "Blue"

    opponent_robots:
      segmentation_algorithm: "FindRobotsColor"
      segmentation_arguments: "Yellow"
      identification_algorithm: "RobotIdentification"
      identification_arguments: "Yellow"
    
    dummy_object:
      segmentation_algorithm: "DummySegmentationAlgorithm"
      identification_algorithm: "DummyIdentificationAlgorithm"

