vision:
    calibration:
        calibrate_match_matrix: false
        calibrate_rectify_matrix: false
        calibrate_team_color: false
    
    team:
      allies: "blue"

    object_list:
     # - "ball"
     - "robots"

    ball:
      segmentation_algorithm: "BallInRangeColorSegmentation"
      identification_algorithm: "DummyIdentificationAlgorithm"

    robots:
      segmentation_algorithm: "FindRobotsColor"
      identification_algorithm: "DummyIdentificationAlgorithm"

