vision:
    calibration:
        calibrate_match_matrix: true
        calibrate_rectify_matrix: true

    object_list:
     - "ball"

    ball:
        segmentation_algorithm: "BallInRangeColorSegmentation"
        identification_algorithm: "DummyIdentificationAlgorithm"
