vision:
    calibration:
        calibrate_match_matrix: false
        calibrate_rectify_matrix: false

    object_list:
     - "ball"
     - "robots"

    ball:
      segmentation_algorithm: "BallInRangeColorSegmentation"
      identification_algorithm: "DummyIdentificationAlgorithm"

    robots:
      segmentation_algorithm: "FindRobots"
      identification_algorithm: "RobotIdentification"

