vision:
    camera:
      show_image: true

    calibration:
        calibrate_match_matrix: false
        calibrate_rectify_matrix: false
        calibrate_team_color: true

    object_list:
     #- "dummy"
     - "ball"
     - "robot_0"
     - "robot_1"
     - "robot_2"

    dummy:
      segmentation_algorithm: "DummySegmentationAlgorithm"
      identification_algorithm: "DummyIdentificationAlgorithm"
    ball:
      segmentation_algorithm: "BallInRangeColorSegmentation"
      identification_algorithm: "BallIdentification"

    robot_0:
      segmentation_algorithm:
       - "HSVInRangeColorSegmentation"
       - "HSVInRangeColorSegmentation"
      segmentation_arguments:
       - "Blue"
       - "Robot0"
      identification_algorithm: "NewRobotIdentification"
      identification_arguments: "robot_0"

    robot_1:
      segmentation_algorithm:
       - "HSVInRangeColorSegmentation"
       - "HSVInRangeColorSegmentation"
      segmentation_arguments:
       - "Blue"
       - "Robot1"
      identification_algorithm: "NewRobotIdentification"
      identification_arguments: "robot_1"

    robot_2:
      segmentation_algorithm:
       - "HSVInRangeColorSegmentation"
       - "HSVInRangeColorSegmentation"
      segmentation_arguments:
       - "Blue"
       - "Robot2"
      identification_algorithm: "NewRobotIdentification"
      identification_arguments: "robot_2"
